bucket_reso_steps = 64
cache_latents = true
cache_latents_to_disk = true
caption_dropout_rate = 0.05
caption_extension = ".txt"
clip_skip = 1
dynamo_backend = "no"
enable_bucket = true
epoch = 3
gradient_accumulation_steps = 1
gradient_checkpointing = true
huber_c = 0.1
huber_schedule = "snr"
learning_rate = 3e-5
logging_dir = "D:/AI Storage/LORA Training/loras-naraka/SD1.5/log"
loss_type = "l2"
lr_scheduler = "constant"
lr_scheduler_args = []
lr_scheduler_num_cycles = 1
lr_scheduler_power = 1
max_bucket_reso = 2048
max_data_loader_n_workers = 0
max_grad_norm = 1
max_timestep = 1000
max_token_length = 75
max_train_steps = 780
min_bucket_reso = 256
min_snr_gamma = 5
mixed_precision = "fp16"
multires_noise_discount = 0.3
network_alpha = 64
network_args = []
network_dim = 64
network_module = "networks.lora"
noise_offset_type = "Original"
optimizer_args = []
optimizer_type = "AdamW"
output_dir = "D:/AI Storage/LORA Training/loras-naraka/SD1.5/model/v 0.1"
output_name = "Nakara"
pretrained_model_name_or_path = "runwayml/stable-diffusion-v1-5"
prior_loss_weight = 1
resolution = "768,768"
sample_prompts = "D:/AI Storage/LORA Training/loras-naraka/SD1.5/model/v 0.1\\prompt.txt"
sample_sampler = "euler_a"
save_every_n_epochs = 1
save_model_as = "safetensors"
save_precision = "fp16"
seed = 1
text_encoder_lr = 3e-5
train_batch_size = 2
train_data_dir = "D:/AI Storage/LORA Training/loras-naraka/SD1.5/img"
unet_lr = 3e-5
xformers = true
